# Generated by Django 5.0.3 on 2024-03-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=2000)),
            ],
        ),
    ]
